### ISSUE TITLE
Neoforge 1.21 Crash when opening Creative Inventory

### ISSUE THREAD

**Issue by unspunreality** [matthewperiut/Chisel-Reborn#45] opened 2024-07-10 00:18 UTC
https://mclo.gs/uBazLJi

So Im not sure the exact cause but Ive been testing all day and a few separate mods are having ctd's when opening creative inventory, including this one. Game loads fine, without this mod enabled I can open my inventory fine, when this mod is enabled I can load the game but then opening inventory ctd's. Im sure theres some growing pains with neoforge going nuts daily but figured Id bring this up to any mods Ive had this happen to me with.

**Comment by matthewperiut** [comment] 2024-07-17 06:27
I can't seem to reproduce, can you please send your prism instance over dropbox or something along those lines?

**Comment by matthewperiut** [comment] 2024-08-01 13:39
Closing because I am unable to reproduce

**Closed** 2024-08-01 13:40 UTC
